# da-collab-ams — wrangler.toml.tpl
#
# Deploy flow (mirrors the helix-cloudflare-*-ams workers):
#   wrangler.toml.tpl (this file, committed — NO customer/env values)
#     → scripts/render-wrangler.js: substitutes $VAR placeholders, leaves @@VERSION@@
#   wrangler.toml (generated, gitignored)
#     → prepare-deploy.js: replaces @@VERSION@@ with the package.json version
#   wrangler-versioned.toml (generated, gitignored)
#     → wrangler deploy -c wrangler-versioned.toml
#
# Required env vars — sourced from ams-eds-terraform's environments/<env>.env
# (generated by scripts/generate-env-file.sh for content_source=da):
#   NODE_ENV                     short env name (worker name suffix + service binding)
#   CLOUDFLARE_ACCOUNT_ID        Cloudflare account ID
#   DA_DOMAIN                    DA domain (route host, ADMIN_ORIGIN, zone)
#
# Secret COLLAB_SHARED_SECRET (shared with da-admin) is pushed via `wrangler secret
# put` by ams-eds-terraform's populate-secrets.sh — not templated here.

name = "da-collab-ams-${NODE_ENV}"
main = "src/edge.js"
compatibility_date = "2023-10-30"
account_id = "${CLOUDFLARE_ACCOUNT_ID}"
keep_vars = true

routes = [{ pattern = "collab.${DA_DOMAIN}/*", zone_name = "${DA_DOMAIN}" }]

services = [
  { binding = "daadmin", service = "da-admin-ams-${NODE_ENV}" }
]

[durable_objects]
bindings = [{ name = "rooms", class_name = "DocRoom" }]

[[migrations]]
tag = "v1"
new_classes = ["DocRoom"]

[dev]
port = 8789

[vars]
ENVIRONMENT = "${NODE_ENV}"
DA_DOMAIN = "${DA_DOMAIN}"
ADMIN_ORIGIN = "https://admin.${DA_DOMAIN}"
VERSION = "@@VERSION@@"
CF_ACCOUNT_ID = "${CLOUDFLARE_ACCOUNT_ID}"
RETURN_STACK_TRACES = "false"
